#!/usr/bin/env zsh

DIR="$( dirname "$0" )"
. "$HOME/.zshrc"

# Ensure pyenv is in profile
file-appender "$DIR/../resources/rc-pyenv.sh" "$HOME/.zshrc"
. "$HOME/.zshrc"

pyenv install 3.12
pyenv global 3.12

python -m pip install pyngrok amazon-orders hookee heliumcli \
                      GitPython Flask pytest coverage mypy Sphinx \
                      plexapi

pyenv install 2.7
pyenv install 3.6
pyenv install 3.9
pyenv install pypy3.10
