#!/usr/bin/env zsh

echo "---------------------------------------------"
echo " Initializing prezto ..."
echo "---------------------------------------------"

if [ ! -d "$HOME/.zprezto" ]; then
  rm -f $HOME/.zshrc
fi

git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

echo "---------------------------------------------"
echo " ... finished prezto setup"
echo "---------------------------------------------"
