#!/usr/bin/env bash

OS_NAME=$(uname -s)
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "============================================="
echo " Initializing $OS_NAME ..."
echo "============================================="

if [[ "$OS_NAME" == "Darwin" ]]; then
  . "$DIR/dev-init-mac-brew"
elif [[ "$OS_NAME" == "Linux" ]]; then
  if [ -f "/etc/debian_version" ]; then
    . "$DIR/dev-init-debian"
  else
    echo "!!> Operating system not supported for automatic provisioning"
    exit 1
  fi
else
  echo "!!> Operating system not supported for automatic provisioning"
  exit 1
fi

chsh -s /bin/zsh

zsh "$DIR/dev-init-prezto"

zsh "$DIR/dev-init-tools"

zsh "$DIR/dev-init-pyenv"

zsh "$DIR/dev-init-jenv"

zsh "$DIR/dev-init-node"

echo "============================================="
echo " ... finished system setup"
echo "============================================="
