#!/usr/bin/env zsh

echo "---------------------------------------------"
echo " Initializing prezto ..."
echo "---------------------------------------------"

if [ -d "$HOME/.zprezto" ]; then
  echo "--> Prezto already installed, updating..."
  git -C "$HOME/.zprezto" pull
  git -C "$HOME/.zprezto" submodule update --init --recursive
else
  rm -f $HOME/.zshrc
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi

echo "---------------------------------------------"
echo " ... finished prezto setup"
echo "---------------------------------------------"
