#!/usr/bin/env zsh


OS_NAME=$(uname -s)
DIR="$( dirname "$0" )"
. "$HOME/.zshrc"

if [[ "$(uname -m)" == "x86_64" ]]; then
  OS_ARCH="amd64"
else
  OS_ARCH="arm64"
fi

echo "---------------------------------------------"
echo " Initializing jenv ..."
echo "---------------------------------------------"

file-appender "$DIR/../lib/rc-jenv.sh" "$HOME/.zshrc"
file-appender "$DIR/../lib/rc-sdk.sh" "$HOME/.zshrc"
. "$HOME/.zshrc"

echo "--> JDK 1.8 must be installed and configured manually, if it is needed"

if [[ "$OS_NAME" == "Darwin" ]]; then
  jenv add /opt/homebrew/opt/openjdk@11
  echo "--> For IntelliJ, add JDK path /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home"
  jenv add /opt/homebrew/opt/openjdk@17
  echo "--> For IntelliJ, add JDK path /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
  jenv add /opt/homebrew/opt/openjdk@21
  echo "--> For IntelliJ, add JDK path /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
  jenv add /opt/homebrew/opt/openjdk
  echo "--> For IntelliJ, add JDK path /opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home"
else
  jenv add /usr/lib/jvm/java-8-openjdk-$OS_ARCH
  jenv add /usr/lib/jvm/java-11-openjdk-$OS_ARCH
  jenv add /usr/lib/jvm/java-17-openjdk-$OS_ARCH
  jenv add /usr/lib/jvm/java-21-openjdk-$OS_ARCH

  sdk install scala 2.13.12
fi

echo "---------------------------------------------"
echo " ... finished jenv setup"
echo "---------------------------------------------"
