#!/usr/bin/env zsh

DIR="$( dirname "$0" )"
. "$HOME/.zshrc"

if [[ "$OS_NAME" == "Darwin" ]]; then
  # Ensure nvm is in profile
  file-appender "$DIR/../resources/rc-nvm.sh" "$HOME/.zshrc"
  . "$HOME/.zshrc"
fi

nvm install 18
nvm install 22