#!/usr/bin/env bash

. "$DIR/../lib/init-helpers.sh"

section_header "Initializing brew"

if ! command -v brew 2>&1 >/dev/null; then
  if [[ "$INTERACTIVE" != "true" ]]; then
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

. "$DIR/../lib/rc-brew.sh"

brew tap hashicorp/tap
brew tap twilio/brew

brew install zsh vim tmux \
             pyenv python@3.12 \
             jenv maven sbt openjdk openjdk@11 openjdk@17 openjdk@21 scala@2.13 \
             autoenv \
             nvm \
             lcov fastlane imagemagick \
             docker docker-completion sqlite \
             ffmpeg bento4 gettext grep gnu-sed wget curl \
             openssl@3 ca-certificates gpg \
             awscli gh twilio hashicorp/tap/terraform

brew install --cask android-commandlinetools

# Symlink autoenv (skip if already exists)
if [[ ! -L "$HOME/.autoenv" ]]; then
  ln -s "$(brew --prefix autoenv)" "$HOME/.autoenv"
fi

. "$DIR/../lib/rc-nvm.sh"
nvm ls 20 2>/dev/null | grep -q "v20" || nvm install 20

section_footer "brew setup"
