#!/usr/bin/env zsh

DIR="$( dirname "$0" )"
. "$HOME/.zshrc"

echo "---------------------------------------------"
echo " Initializing node ..."
echo "---------------------------------------------"

file-appender "$DIR/../lib/rc-nvm.sh" "$HOME/.zshrc"
. "$HOME/.zshrc"

nvm install 18
nvm install 22

echo "---------------------------------------------"
echo " ... finished node setup"
echo "---------------------------------------------"
