#!/usr/bin/env bash

echo "---------------------------------------------"
echo " Initializing brew ..."
echo "---------------------------------------------"

if ! command -v brew 2>&1 >/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

. "$DIR/../lib/rc-brew.sh"

brew tap twilio/brew

brew install zsh vim tmux \
             pyenv python@3.12 \
             jenv maven sbt openjdk openjdk@11 openjdk@17 openjdk@21 scala@2.13 \
             autoenv \
             nvm node@18 \
             docker docker-completion sqlite \
             ffmpeg bento4 gettext grep wget curl \
             openssl@3 ca-certificates \
             awscli gh twilio terraform

ln -s "$(brew --prefix autoenv)" "$HOME/.autoenv"

echo "---------------------------------------------"
echo " ... finished brew setup"
echo "---------------------------------------------"
