#!/usr/bin/env zsh

OS_NAME=$(uname -s)
DIR="$( dirname "$0" )"
. "$DIR/../lib/init-helpers.sh"

section_header "Initializing dev tools/dotfiles"

# Add alexdlaird/bin to path
"$DIR/../bin/block-manager" "$DIR/../lib/rc-alexdlaird-bin.sh" "$HOME/.zshrc" "alexdlaird-bin"
. "$DIR/../lib/rc-alexdlaird-bin.sh"

# Run background refresh tasks on terminal open
block-manager "$DIR/../lib/rc-refresh.sh" "$HOME/.zshrc" "refresh"

if [[ "$OS_NAME" == "Darwin" ]]; then
  block-manager "$DIR/../lib/rc-brew.sh" "$HOME/.zshrc" "brew"
fi

block-manager "$DIR/../lib/rc-autoenv.sh" "$HOME/.zshrc" "autoenv"

# Add preferred editors to profile
block-manager "$DIR/../lib/rc-editors.sh" "$HOME/.zshrc" "editors"

# Install public SSH key
mkdir -p "$HOME/.ssh"
block-manager "$DIR/../lib/id_rsa.pub" "$HOME/.ssh/authorized_keys" "alexdlaird-pubkey"

# Initialize Git configs
git config --global --replace-all core.excludesFile "$HOME/.gitignore_global"
git config --global user.name "Alex Laird"
git config --global user.email "contact@alexlaird.com"
block-manager "$DIR/../lib/.gitignore_global" "$HOME/.gitignore_global" "alexdlaird-gitignore"

# Initialize vim config (use " for vim comments)
block-manager "$DIR/../lib/.vimrc" "$HOME/.vimrc" "alexdlaird-vimrc" '"'

# Initialize hosts
HOSTS_FILE="$DIR/../env/hosts"
if [ -f "$HOSTS_FILE" ]; then
  block-manager "$HOSTS_FILE" "/etc/hosts" "alexdlaird-hosts"
fi

section_footer "dev tools/dotfiles setup"
